# Copyright © 2015 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Assure yum is installed
  command: bash -c "rpm -q yum || tdnf install -y yum" creates=/usr/bin/yum

- name: Assure sudo installed
  yum: pkg={{ item }} state=installed
  with_items:
    - sudo

- name: Assure groups created for all users
  group: name={{ item.group }} state=present
  with_items: "{{ sudo_users }}"

- name: Assure sudo users created
  user:
    name: "{{ item.userid }}"
    groups: "{{ item.group }}"
    state: present
    append: yes
  with_items: "{{ sudo_users }}"

- name: Setup passwordless sudo
  template:
    src=sudoers.j2
    dest="/etc/sudoers.d/{{ item.userid }}"
    owner=root
    group=root
    mode=0600
  with_items: "{{ sudo_users }}"

# Fixup sudoers file
# This is necessary so users don't get overidden unexpectedly
# by commands after the include in /etc/sudoers

- name: check if includedir is last in file
  command: bash -c "tail -n1 /etc/sudoers | grep '#includedir /etc/sudoers.d'"
  register: sudo_include_on_last_line
  changed_when: false
  ignore_errors: yes

- name: Remove, temporarily, the includedir line from /etc/sudoers
  lineinfile: dest=/etc/sudoers state=absent line="#includedir /etc/sudoers.d"
  when: sudo_users|length > 0 and sudo_include_on_last_line.rc != 0

- name: Insert the includedir line last in /etc/sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='#includedir /etc/sudoers.d' line="#includedir /etc/sudoers.d"
  when: sudo_users|length > 0
